# Generated by Django 2.2.1 on 2019-06-02 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliticTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('published_date', models.DateField()),
                ('categoria', models.ManyToManyField(to='appdigilib.Categoria')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appdigilib.Image')),
                ('task', models.ManyToManyField(to='appdigilib.AnaliticTask')),
            ],
        ),
    ]
