# Generated by Selenium IDE
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestTest1InserirCategoria(unittest.TestCase):

  def setUp(self):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1InserirCategoria(self):
    self.driver.get("http://127.0.0.1:8000/admin/login/?next=/admin/")
    self.driver.set_window_size(1299, 608)
    self.driver.find_element(By.ID, "id_username").send_keys("adia");
    self.driver.find_element(By.ID, "id_password").send_keys("Adila123");
    self.driver.find_element_by_class_name("submit-row").click();
    self.driver.find_element(By.LINK_TEXT, "Categorys").click()
    self.driver.find_element(By.CSS_SELECTOR, ".addlink").click()
    self.driver.find_element(By.ID, "id_category").click()
    self.driver.find_element(By.ID, "id_category").send_keys("FLOW")
    self.driver.find_element(By.NAME, "_save").click()
    self.driver.find_element(By.CSS_SELECTOR, "#user-tools > a:nth-child(2)").click()
  
